import 'package:flutter/material.dart';
import 'package:widgets/core/my_button.dart';

List<Widget> buttons = [
  CustomElevatedButton(
    yazi: 'Clippers',
    primary: Colors.amber,
    onprimary: Colors.black,
    rota: '/clippers',
  ),
  CustomElevatedButton(
    yazi: 'Glass Morphism',
    primary: Colors.red,
    onprimary: Colors.white,
    rota: '/glass',
  ),
  CustomElevatedButton(
    yazi: 'Neu Morphism',
    primary: Colors.green,
    onprimary: Colors.black,
    rota: '/neumorp',
  ),
  CustomElevatedButton(
    yazi: 'Flexible',
    primary: Colors.purple,
    onprimary: Colors.white,
    rota: '/flexible',
  ),
  CustomElevatedButton(
    yazi: 'Check Box',
    primary: Colors.blueGrey,
    onprimary: Colors.black,
    rota: '/checkbox',
  ),
  CustomElevatedButton(
    yazi: 'Clip RRect',
    primary: Colors.blue,
    onprimary: Colors.white,
    rota: '/cliprrect',
  ),
  CustomElevatedButton(
    yazi: 'I.Viewer',
    primary: Colors.pinkAccent,
    onprimary: Colors.black,
    rota: '/viewer',
  ),
  CustomElevatedButton(
    yazi: 'Selectable',
    primary: Colors.deepOrange,
    onprimary: Colors.white,
    rota: '/selectable',
  ),
  CustomElevatedButton(
    yazi: 'Alert Dialog',
    primary: Colors.purpleAccent,
    onprimary: Colors.black,
    rota: '/alert',
  ),
  CustomElevatedButton(
    yazi: 'Spread Operator',
    primary: Colors.black87,
    onprimary: Colors.white,
    rota: '/spread',
  ),
  CustomElevatedButton(
    yazi: 'Visibility',
    primary: Colors.white70,
    onprimary: Colors.black,
    rota: '/visibility',
  ),
  CustomElevatedButton(
    yazi: 'Positioned',
    primary: Colors.indigo,
    onprimary: Colors.white,
    rota: '/positioned',
  ),
  CustomElevatedButton(
    yazi: 'Fitted Box',
    primary: Colors.deepOrangeAccent,
    onprimary: Colors.black,
    rota: '/fitted',
  ),
  CustomElevatedButton(
    yazi: 'Stack',
    primary: Colors.green,
    onprimary: Colors.white,
    rota: '/stack',
  ),
  CustomElevatedButton(
    yazi: 'Table',
    primary: Colors.blueAccent,
    onprimary: Colors.black,
    rota: '/table',
  ),
  CustomElevatedButton(
    yazi: 'Adaptive',
    primary: Colors.blueGrey,
    onprimary: Colors.white,
    rota: '/adaptive',
  ),
  CustomElevatedButton(
    yazi: 'Spacer',
    primary: Colors.brown,
    onprimary: Colors.black,
    rota: '/spacer',
  ),
  CustomElevatedButton(
    yazi: 'Future',
    primary: Colors.deepPurple,
    onprimary: Colors.white,
    rota: '/future',
  ),
  CustomElevatedButton(
    yazi: 'Stream Builder',
    primary: Colors.cyan,
    onprimary: Colors.black,
    rota: '/stream',
  ),
  CustomElevatedButton(
    yazi: 'Stream Builder2',
    primary: Colors.lime,
    onprimary: Colors.white,
    rota: '/stream2',
  ),
  CustomElevatedButton(
    yazi: 'Navigation Bar',
    primary: Colors.grey,
    onprimary: Colors.black,
    rota: '/navigationbar',
  ),
  CustomElevatedButton(
    yazi: 'Tooltip',
    primary: Colors.indigo,
    onprimary: Colors.white,
    rota: '/tooltip',
  ),
  CustomElevatedButton(
    yazi: 'Date Picker',
    primary: Colors.greenAccent,
    onprimary: Colors.black,
    rota: '/date',
  ),
  CustomElevatedButton(
    yazi: 'WillPopScope',
    primary: Colors.lightBlue,
    onprimary: Colors.white,
    rota: '/will',
  ),
  CustomElevatedButton(
    yazi: 'Simple Dialog',
    primary: Colors.orange,
    onprimary: Colors.black,
    rota: '/dialog',
  ),
  CustomElevatedButton(
    yazi: 'Animated Cross Fade',
    primary: Colors.pink,
    onprimary: Colors.white,
    rota: '/anime',
  ),
  CustomElevatedButton(
    yazi: 'Modal Bottom Sheet',
    primary: Colors.purple,
    onprimary: Colors.black,
    rota: '/modal',
  ),
  CustomElevatedButton(
    yazi: 'Stepper',
    primary: Colors.purpleAccent,
    onprimary: Colors.white,
    rota: '/stepper',
  ),
  CustomElevatedButton(
    yazi: 'Page View',
    primary: Colors.red,
    onprimary: Colors.black,
    rota: '/pageview',
  ),
  CustomElevatedButton(
    yazi: 'Bottom Bar',
    primary: Colors.teal,
    onprimary: Colors.white,
    rota: '/bottom',
  ),
  CustomElevatedButton(
    yazi: 'PopUp Menu',
    primary: Colors.redAccent,
    onprimary: Colors.black,
    rota: '/popup',
  ),
  CustomElevatedButton(
    yazi: 'PopUp Menu',
    primary: Colors.black,
    onprimary: Colors.white,
    rota: '/range',
  ),
  CustomElevatedButton(
    yazi: 'Time Picker',
    primary: Colors.yellow,
    onprimary: Colors.black,
    rota: '/time',
  ),
  CustomElevatedButton(
    yazi: 'Wrap',
    primary: Colors.cyan,
    onprimary: Colors.white,
    rota: '/wrap',
  ),
  CustomElevatedButton(
    yazi: 'Expansion Tile',
    primary: Colors.deepOrange,
    onprimary: Colors.black,
    rota: '/expansion',
  ),
];
